# Name of the project
PROJECT_NAME = SCHOOL_BILLING_SYSTEM

#Doxyfile folder
DOC = documentation

#All source code files
SRC = school.c\
src/school_operations.c

#All test source files
TEST_SRC = src/school_operations.c\
test/test_school_operations.c\
unity/unity.c

TEST_OUTPUT = Test_a.out

#All include folders with header files
INC = -Iinc\
-Iunity\

#Project Output Name
PROJECT_OUTPUT = school.out

#Document files
DOCUMENTATION_OUTPUT = documentation/html


Build:
	gcc function1.c test_school.c unity/unity.c -Iunity

Run:
	./a.out